/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-background": "#dce4e4",
        "inverse-surface": "#dce4e4",
        "on-secondary-container": "#002c4b",
        "error": "#ffb4ab",
        "on-tertiary-container": "#00678c",
        "outline": "#849495",
        "secondary-fixed": "#d0e4ff",
        "surface-variant": "#2e3637",
        "on-secondary-fixed-variant": "#004a7a",
        "on-tertiary": "#00354a",
        "surface-container-high": "#232b2c",
        "inverse-on-surface": "#2a3232",
        "primary-fixed": "#6ff6ff",
        "tertiary-container": "#b2e1ff",
        "surface-container-low": "#151d1e",
        "surface-tint": "#00dce6",
        "tertiary-fixed": "#c4e7ff",
        "surface-bright": "#333b3b",
        "tertiary-fixed-dim": "#7bd0ff",
        "secondary-container": "#3196e6",
        "primary-fixed-dim": "#00dce6",
        "inverse-primary": "#00696f",
        "on-surface-variant": "#b9cacb",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#002022",
        "on-tertiary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-container-highest": "#2e3637",
        "primary-container": "#00f2fe",
        "surface-container-lowest": "#081010",
        "on-primary": "#00373a",
        "primary": "#e0fdff",
        "on-primary-fixed-variant": "#004f53",
        "on-surface": "#dce4e4",
        "secondary": "#9bcbff",
        "error-container": "#93000a",
        "surface": "#0d1515",
        "tertiary": "#f1f8ff",
        "surface-dim": "#0d1515",
        "on-secondary-fixed": "#001d34",
        "on-secondary": "#003256",
        "outline-variant": "#3a494b",
        "on-error": "#690005",
        "secondary-fixed-dim": "#9bcbff",
        "background": "#0d1515",
        "on-primary-container": "#006a70",
        "surface-container": "#192122",
        "warning": "#f59e0b"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "margin": "2rem"
      },
      "fontFamily": {
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"]
      },
      "fontSize": {
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
